### PR TITLE
Contract Address Update

### PR DESCRIPTION
**Pull request by muku314115**
Fixes #

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.8.0 and above.
- [x] I ran pre-commit checks against my changes.
- [x] I've written tests against my changes and all the current present tests are passing.

### Current behaviour
Outdated Contract address

### New expected behaviour
New Contract address

### CODE REVIEW

**Review by xadahiya — APPROVED** [review]
LGTM!

**Review by anomit — APPROVED** [review]
LGTM

**Comment by anomit** [comment]
Apart from the contract address update, this release also requires a new sequencer ID to be included in the `env.example`.

**Review by xadahiya — APPROVED** [review]
LGTM!

**Review by anomit — APPROVED** [review]
Approving updated protocol state contract

**Review by xadahiya — APPROVED** [review]
Approving again since the Protocol State contract address was changed.

**Pull request merged**
